# -*- coding: utf-8 -*-
"""
visualise_peristalsis.py
========================
Reads peristalsis DAC command CSV files and plots the 12-layer trajectories.

Generated by: Dhruvesh Bhatta  (based on data by Steven Dirven, PhD)

Layout
------
Figure 1 -- Speed variation  : 40 mm amplitude at 20 / 30 / 40 mm/s
Figure 2 -- Amplitude variation: 40 / 50 / 60 mm at 20 mm/s
Figure 3 -- Staircase step responses (all-layer simultaneous steps)
Figure 4 -- FSP calibration ramps (uniform pressure sweeps)
Figure 5 -- Travelling wave heatmaps

Each subplot shows all 12 layer traces colour-coded by layer index.
Interactive: use toolbar to zoom/pan, hover to see (time, DAC, layer).
"""

import os
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from matplotlib.widgets import Cursor

# ---------------------------------------------------------------------------
# Style & backend
# ---------------------------------------------------------------------------
plt.style.use('seaborn-v0_8-whitegrid')
plt.rcParams.update({
    'figure.dpi':         100,
    'savefig.dpi':        200,
    'font.size':          11,
    'axes.titlesize':     13,
    'axes.labelsize':     12,
    'xtick.labelsize':    10,
    'ytick.labelsize':    10,
    'legend.fontsize':    9,
    'figure.titlesize':   14,
    'lines.linewidth':    1.4,
    'axes.grid':          True,
    'grid.alpha':         0.35,
    'grid.linestyle':     '--',
})

DATA_DIR = os.path.dirname(os.path.abspath(__file__))
_cursors = []   # prevent garbage collection of interactive widgets


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def load(filename):
    """Load a CSV from the PeristalsisData directory."""
    return np.genfromtxt(os.path.join(DATA_DIR, filename), delimiter=',')


def layer_colors(n=12):
    """Return n colours spanning a colourmap."""
    return [cm.plasma(i / (n - 1)) for i in range(n)]


def plot_layers(ax, data, title, ts=0.1, ylabel='DAC command'):
    """Plot all 12 layer columns with a shared legend and hover-friendly lines."""
    colors = layer_colors(data.shape[1])
    time = np.arange(data.shape[0]) * ts
    for col in range(data.shape[1]):
        ax.plot(time, data[:, col], color=colors[col], label=f'L{col}',
                picker=3)          # 3-pixel tolerance for click events
    ax.set_title(title, fontweight='bold')
    ax.set_ylabel(ylabel)
    ax.set_xlabel('Time (s)')
    ax.set_ylim(bottom=-5)


def add_shared_legend(fig, ncol=6):
    """Single legend for all 12 layers at bottom of figure."""
    handles, labels = fig.axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc='lower center', ncol=ncol,
               frameon=True, fancybox=True, shadow=True,
               bbox_to_anchor=(0.5, -0.01))


def add_crosshair(fig):
    """Add crosshair cursors to every axes in fig."""
    for ax in fig.axes:
        c = Cursor(ax, useblit=True, color='grey', linewidth=0.6)
        _cursors.append(c)


# ---------------------------------------------------------------------------
# Figure 1 — Speed variation  (amplitude fixed at ~40 mm)
# ---------------------------------------------------------------------------
speed_files = [
    ('40mmat20mmps_Dips.csv',  '40 mm @ 20 mm/s  (Ts ≈ 0.075 s)', 0.075),
    ('40mmat30mmps_Dips.csv',  '40 mm @ 30 mm/s  (Ts ≈ 0.115 s)', 0.115),
    ('40mmat40mmps_Dips.csv',  '40 mm @ 40 mm/s  (Ts ≈ 0.107 s)', 0.107),
]

fig1, axes1 = plt.subplots(3, 1, figsize=(14, 10), constrained_layout=True)
fig1.suptitle('Speed Variation — 12-Layer DAC Commands\n'
              '(Amplitude ≈ 40 mm, wave travels Layer 10 → Layer 0)',
              fontweight='bold')
for ax, (fn, ttl, ts) in zip(axes1, speed_files):
    plot_layers(ax, load(fn), ttl, ts=ts)
add_shared_legend(fig1)
add_crosshair(fig1)

# ---------------------------------------------------------------------------
# Figure 2 — Amplitude variation  (speed fixed at 20 mm/s)
# ---------------------------------------------------------------------------
amp_files = [
    ('40mmat20mmps_Dips.csv',  '40 mm @ 20 mm/s', 0.075),
    ('50mmat20mmps_Dips.csv',  '50 mm @ 20 mm/s', 0.075),
    ('60mmat20mmps_Dips.csv',  '60 mm @ 20 mm/s', 0.075),
]

fig2, axes2 = plt.subplots(3, 1, figsize=(14, 10), constrained_layout=True)
fig2.suptitle('Amplitude Variation — 12-Layer DAC Commands\n'
              '(Speed = 20 mm/s, Ts = 0.075 s)', fontweight='bold')
for ax, (fn, ttl, ts) in zip(axes2, amp_files):
    plot_layers(ax, load(fn), ttl, ts=ts)
add_shared_legend(fig2)
add_crosshair(fig2)

# ---------------------------------------------------------------------------
# Figure 3 — Staircase step responses
# ---------------------------------------------------------------------------
stair_files = [
    ('Peristalsis_Staircase_0_80_20mmps.csv',  '0 → 80 DAC  (all 12 layers)',  0.075),
    ('Peristalsis_Staircase_0_100_20mmps.csv', '0 → 100 DAC (all 12 layers)',  0.075),
    ('Peristalsis_Staircase_0_130_20mmps.csv', '0 → 130 DAC (all 12 layers)',  0.075),
    ('Peristalsis_Staircase_0_140_20mmps.csv', '0 → 140 DAC (all 12 layers)',  0.075),
]

fig3, axes3 = plt.subplots(4, 1, figsize=(14, 12), constrained_layout=True)
fig3.suptitle('Staircase Step Responses — All 12 Layers\n'
              '(Static characterisation / system ID)', fontweight='bold')
for ax, (fn, ttl, ts) in zip(axes3, stair_files):
    plot_layers(ax, load(fn), ttl, ts=ts)
add_shared_legend(fig3)
add_crosshair(fig3)

# ---------------------------------------------------------------------------
# Figure 4 — FSP / ESR calibration ramps
# ---------------------------------------------------------------------------
fsp_files = [
    ('FSPPeristalsisFSP_ESR_traj_40mmps_90.csv',  '30 → 90 DAC ramp  (+2/step)',  0.107),
    ('FSPPeristalsisFSP_ESR_traj_40mmps_100.csv', '30 → 100 DAC ramp (+2/step)',  0.107),
    ('FSPPeristalsisFSP_ESR_traj_40mmps_110.csv', '30 → 110 DAC ramp (+2/step)',  0.107),
]

fig4, axes4 = plt.subplots(3, 1, figsize=(14, 10), constrained_layout=True)
fig4.suptitle('FSP Calibration Ramps — All 12 Layers Uniform\n'
              '(Full-Scale Pressure / ESR curves)', fontweight='bold')
for ax, (fn, ttl, ts) in zip(axes4, fsp_files):
    plot_layers(ax, load(fn), ttl, ts=ts)
add_shared_legend(fig4)
add_crosshair(fig4)

# ---------------------------------------------------------------------------
# Figure 5 — Side-by-side heatmaps: travelling wave at 3 speeds
# ---------------------------------------------------------------------------
fig5, axes5 = plt.subplots(1, 3, figsize=(18, 6), constrained_layout=True)
fig5.suptitle('Peristaltic Travelling Wave — Heatmap (Layer × Time)\n'
              'Colour = DAC command  |  Amplitude = 40 mm', fontweight='bold')

for ax, (fn, ttl, ts) in zip(axes5, speed_files):
    data = load(fn)
    time = np.arange(data.shape[0]) * ts
    im = ax.imshow(data.T, aspect='auto', origin='lower', cmap='hot',
                   vmin=35, vmax=125,
                   extent=[time[0], time[-1], -0.5, 11.5])
    ax.set_title(ttl, fontweight='bold')
    ax.set_xlabel('Time (s)')
    ax.set_ylabel('Layer index')
    ax.set_yticks(range(12))
    fig5.colorbar(im, ax=ax, label='DAC value', shrink=0.85, pad=0.02)
add_crosshair(fig5)

# ---------------------------------------------------------------------------
plt.show()
